Portal.2c2p/Controllers/UploadFileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BizLogic._2c2p;

namespace Portal._2c2p.Controllers
{
    public class UploadFileController : Controller
    {
        
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            try
            {
                if (file.ContentLength > 0)
                {                  
                    ViewBag.Message = SaveFile(file);
                }
                return View();
            }
            catch
            {
                ViewBag.Message = "File upload failed!!";
                return View();
            }
        }
        private string SaveFile(HttpPostedFileBase file2upload)
        {
            try
            {
                string fileExtension = Path.GetExtension(file2upload.FileName);
                int fileSize = file2upload.ContentLength;
                if (string.IsNullOrEmpty(fileExtension))
                {
                    return "Unknown format!";
                }
                else if (fileExtension.ToLower() != ".csv" && fileExtension.ToLower() != ".xml")
                {
                    return "Invalid file format! Only file with csv or xml extension are allowed.";
                }
                else if (fileSize > 1048576)
                {
                    return "Max file size (1MB) exceeded!";
                }
                else
                {
                    string _FileName = Path.GetFileName(file2upload.FileName);
                    string _path = Path.Combine(Server.MapPath("App_Data/UploadedFiles"), _FileName);
                    file2upload.SaveAs(_path);
                    return DataFileBL.ProcessFile(_path,fileExtension);
                   
                }
            }
            catch (Exception ex)
            {
                return "File upload failed!!";
            }
           
        }

    }
}

Portal.2c2p/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        @ViewBag.Title - My Web Portal
    </title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Web Portal", "Index", "UploadFile", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Web Portal</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Portal.2c2p/Views/UploadFile/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Upload Data File</h2>

@using (Html.BeginForm("Index", "UploadFile", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div>

    @Html.TextBox("file", "", new { type = "file" }) <br /> <br />
    <input type="submit" value="Upload" /> <br /> <br />
    @ViewBag.Message
    
</div>


}  